import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/base/Navbar";
import Footer from "@/components/base/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kalalkriti",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />

        {/* Global blurred background elements */}
        <div className="fixed top-20 left-10 w-72 h-72 bg-orange-300/30 rounded-full blur-3xl -z-10 pointer-events-none" />
        <div className="fixed bottom-20 right-10 w-72 h-72 bg-rose-300/30 rounded-full blur-3xl -z-10 pointer-events-none" />

        {children}
        <Footer/>
      </body>
    </html>
  );
}
